services:
  # This is a simple noop container that blocks until the migrator container has completed.
  postgres_migrated:
    image: alpine:3.14
    depends_on:
      migrator:
        condition: service_completed_successfully
    command: echo "Migrations completed"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: oops_my_turn
      POSTGRES_USER: oops_my_turn
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U oops_my_turn" ]
      interval: 1s
      timeout: 5s
      retries: 10

  migrator:
    depends_on:
      postgres:
        condition: service_healthy
    image: golang:1.25
    environment:
      DB_MIGRATIONS_ENABLED: true
      DB_HOST: postgres
      DB_USER: oops_my_turn
      DB_PASSWORD: 12345
      DB_NAME: oops_my_turn
    volumes:
      - "./:/app"
    entrypoint: "/bin/sh -c"
    command:
      - cd /app && go run cmd/migrate/main.go
